import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { getCssText, styled } from "@/styles";


import { globalStyles } from '@/styles/global'
import { Header } from "@/components/header";

globalStyles()

const roboto = Roboto({
  weight: ["400", "700"],
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const Container = styled("div", {
  display: "flex",
  flexDirection: "column",
  alignItems: "flex-start",
  justifyContent: "center",
  minHeight: "100vh"
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style id="stitches" dangerouslySetInnerHTML={{ __html: getCssText() }} />
      </head>
      <body className={`${roboto.variable}`}>
        <Container>
          <Header />
          {children}
        </Container>
      </body>
    </html>
  );
}


